Fix: Error document
casbin/casbin-website pull request #175
Opened 2021-03-08 14:03 UTC by Kininaru

Fix: https://github.com/casbin/casbin-website/issues/174

2021-03-08 15:32 UTC, Zxilly requested changes

2021-03-08 15:32 UTC, Zxilly commented on docs/WebpageController.md
> +result.then((success, failed) => {
same here

2021-03-08 15:32 UTC, Zxilly commented on docs/WebpageController.md
> +result.then((success, failed) => {
same here

2021-03-08 15:32 UTC, Zxilly commented on docs/WebpageController.md
> +result.then((success, failed) => {
There is no need for `failed`, enforcer will never reject

2021-03-08 15:41 UTC, Kininaru commented on docs/WebpageController.md
> +result.then((success, failed) => {
The electricity in our dormitory has been cut off. I will fix that tomorrow.

2021-03-09 05:25 UTC, Zxilly approved these changes

2021-03-09 05:42 UTC, merged