docs: add GetImplicitResourcesForUser and GetImplicitUsersForRole
casbin/casbin-website pull request #224
Opened 2021-05-27 08:46 UTC by closetool

Signed-off-by: closetool <4closetool3@gmail.com>

Fix: casbin/casbin#798

2021-05-27 09:08 UTC, hsluoyz commented
@ErikQQY plz review.

2021-05-27 09:24 UTC, ErikQQY approved these changes
LGTM

2021-05-27 12:56 UTC, hsluoyz requested changes

2021-05-27 12:56 UTC, hsluoyz commented on docs/RBACAPI.md
> +users := e.GetImplicitRolesForUser("role:user")
Is it on earth `GetImplicitUsersForRole()` or `GetImplicitRolesForUser()`?

2021-05-27 12:56 UTC, hsluoyz commented on docs/RBACAPI.md
> +Get("role:user") can only get: ["role:admin"].
What's `Get()`?

2021-05-27 12:56 UTC, hsluoyz commented on docs/RBACAPI.md
> +But GetImplicitRolesForUser("alice") will get: ["role:admin", "alice"].
Are you sure `GetImplicitRolesForUser("alice") will get: ["role:admin", "alice"].` is correct?

2021-05-27 14:57 UTC, closetool commented
@hsluoyz fixed, sorry for my mistakes.

2021-05-28 01:49 UTC, hsluoyz requested changes

2021-05-28 01:49 UTC, hsluoyz commented on docs/RBACAPI.md
> +But GetImplicitUesrsForRole("alice") will get: ["role:admin", "alice"].
Wrong here?

![image](https://user-images.githubusercontent.com/3787410/119917891-fd916d80-bf99-11eb-9a15-05505bc0c80c.png)

2021-05-28 05:32 UTC, hsluoyz approved these changes

2021-05-28 05:32 UTC, merged