feat: add lua getstarted at /docs/GetStarted.md
casbin/casbin-website pull request #241
Opened 2021-06-20 11:42 UTC by Edmond-J-A

2021-06-20 15:41 UTC, hsluoyz commented
@techoner @ErikQQY plz reivew.

2021-06-22 02:25 UTC, ErikQQY requested changes
Please fix it @Edmond-J-A

2021-06-22 09:26 UTC, ErikQQY commented on docs/GetStarted.md
> +you can add --local behind your command like this to fix:
Sorry, I might not be clear, Docusaurus codeblock supports multi-line codes in one tab, so instead of putting all of the latter section out of the codeblock, I think it would be great to put this to the Lua tab

```
luarocks install casbin
```
If report Error: Your.....
```
luarocks install casbin --local
```

2021-06-23 05:12 UTC, ErikQQY commented
Good job!

2021-06-24 15:48 UTC, techoner requested changes

2021-07-01 08:10 UTC, Zxilly commented
@Edmond-J-A plz sign off with **your** meaningful email, but not something like `you@example.com`

2021-07-01 08:11 UTC, Zxilly requested changes
Please use your real email address

2021-07-03 03:46 UTC, Edmond-J-A commented
@hsluoyz plz review.

2021-07-03 04:01 UTC, merged