feat: add "subjectPriority(p.eft) || deny" feature
casbin/casbin-website pull request #254
Opened 2021-07-15 03:48 UTC by tangyang9464

Signed-off-by: tangyang9464 <tangyang9464@163.com>

fix: #252

2021-07-15 05:48 UTC, hsluoyz requested changes

2021-07-15 05:48 UTC, hsluoyz commented on docs/PriorityModel.md
> +The inherited structure of roles and users can only be multiple trees, not graphs.
Put these lines into a paragraph. Don't use multiple single sentences.

2021-07-15 11:32 UTC, hsluoyz commented
@ErikQQY plz review carefully, especially for grammar errors, link errors, etc.

2021-07-15 15:21 UTC, ErikQQY requested changes

2021-07-15 15:21 UTC, ErikQQY commented on docs/SupportedModels.md
> +
The subject_priority_model.csv link doesn't work

2021-07-15 15:21 UTC, ErikQQY commented on docs/SyntaxForModels.md
To link to other docs, please refer to other examples, instead of using netlify links.

2021-07-16 02:44 UTC, tangyang9464 commented
@ErikQQY fixed

2021-07-16 03:31 UTC, hsluoyz approved these changes

2021-07-16 03:32 UTC, merged