Add reference to new GraphQL middleware in Python
casbin/casbin-website pull request #341
Opened 2022-05-20 21:08 UTC by Checho3388

The goal of this change is to add a reference to [`graphql-authz`](https://github.com/Checho3388/graphql-authz) middleware written in Python.

2022-05-20 21:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/casbin-website?pullRequest=341) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/casbin-website?pullRequest=341) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/casbin-website?pullRequest=341) it.</sub>

2022-05-21 02:15 UTC, hsluoyz requested changes

2022-05-21 02:15 UTC, hsluoyz commented on docs/GraphQLMiddlewares.md
> +[graphql-authz](https://github.com/node-casbin/graphql-authz) | [GraphQL-core 3](https://github.com/graphql-python/graphql-core) | [@Checho3388](https://github.com/Checho3388) | A Casbin authorizatio
Wrong link: https://github.com/node-casbin/graphql-authz

2022-05-21 02:56 UTC, Checho3388 commented on docs/GraphQLMiddlewares.md
> +[graphql-authz](https://github.com/node-casbin/graphql-authz) | [GraphQL-core 3](https://github.com/graphql-python/graphql-core) | [@Checho3388](https://github.com/Checho3388) | A Casbin authorizatio
Sorry. Fixed!

2022-05-21 04:45 UTC, hsluoyz approved these changes

2022-05-21 04:45 UTC, merged